### ISSUE TITLE
Protocol version should be a string, not an int

### ISSUE THREAD

**Issue by dsp-ant** [modelcontextprotocol/modelcontextprotocol#1]
This would allow us to do SemVer in the protocol, or version with dates, or any number of other, more flexible strategies.

**Comment by dsp-ant** [comment]
@jspahrsummers this was originally a task created by you, before moving it over. 

I don't like using semver for wire protocols. My reason is very similar to this discussion on Etherium: https://github.com/libp2p/specs/issues/203

 * Semver adds complexity by requiring all clients and servers to correctly deal with it, effectively forcing them to take a dependency (assuming they don't use an SDK).
 * Even between two patch version with backwards compatibility it's not clear what the implications of an added optional field are at a given time, and they might widely vary between different types of changes. The result of two clients with different versions is unpredictable, particularly if you consider the combinatorial explosion over multiple versions. 
  * This assumes that we get it right to adhere to semver, which historically all projects have struggled with and broken at some point or another.
  
I think the right approach here is allowing clients and servers to negotiate over a range over versions instead of a single version, but still making each version a simple monotonically increasing integer. This means client A can advertise version [1,2,3] whereas server B can say it only speaks [1,2]. Of course this would still add a lot of complexity on clients that want to support multiple versions, but i think that's okay, at least in that case they must make the implications explicit in code.

**Comment by jspahrsummers** [comment]
If the version is a monotonically increasing integer, do we basically expect to rev it with **every** commit to the spec? It seems unavoidable, because we aren't defining what "compatibility" means across those integer versions.

My concern is something like:
* Servers may get written once and then rarely updated
* We should expect that clients are updated frequently
* To support those rarely updated servers, do clients need to advertise support for **hundreds** of versions? How would an implementor even keep track of that level of support?

**Comment by jspahrsummers** [comment]
At the very least, a date seems preferable, because then we could say, "I support anything authored after this date."

**Comment by dsp-ant** [comment]
I like using dates a lot. Thats actually best. I still think we go through a release cycle and only bump when there is a release, similarly as we wouldn't bump a semver patch on every commit. So the current version is always in DRAFT, and then every 3 month we release a new version. (we can decide if we go for cadence based or 'when ready' release cycle, but thats a different discussion)

**Comment by jspahrsummers** [comment]
Great, sounds good to me. Then we still need to make this change to turn it into a string. (`YYYYmmdd` probably)

**Comment by dsp-ant** [comment]
Why would it need to be a string?

**Comment by jspahrsummers** [comment]
I think it's needlessly confusing to represent dates as an integer—usually that would indicate a Unix timestamp, not a date-string-encoded-as-integer.

**Comment by dsp-ant** [comment]
As long as they don't need to do relational comparison. It's probably fine to use strings.

**Comment by jspahrsummers** [comment]
Any date format that orders as `YYYYmmdd` or similar, and always includes leading zeroes, would support a lexicographical comparison too. (This was one of the key design principles of ISO-8601)

**Comment by kmkarakaya** [comment]
Please list the files in the report.

**Comment by atlastrinity** [comment]
Test comment from MCP server testing - verifying add_issue_comment functionality works correctly
