### ISSUE TITLE
Support for Pagination

### ISSUE THREAD

**Issue by dsp-ant** [modelcontextprotocol/modelcontextprotocol#6]
Of resources, prompts, tools, etc.

This should probably be optional (e.g., page size at the discretion of the server), so as not to complicate servers that don't need it.

**Comment by benjaminbelaga** [comment]
I've been running a production MCP server for Google Workspace (Gmail + Calendar)
  on a remote VPS for a few weeks now. Here's my setup:

  **Architecture:**
  - FastAPI/FastMCP on a Contabo VPS
  - Nginx reverse proxy with SSL (Let's Encrypt)
  - Google OAuth 2.0 for Workspace authentication
  - Token persistence with auto-refresh

  **Key learnings:**
  1. Store tokens in a secure location with proper file permissions
  2. Handle token refresh gracefully - the refresh_token from Google lasts ~6 months
  3. Use systemd for process management with auto-restart

  **Repo:** github.com/benjaminbelaga/mcp-google-workspace

  Happy to share more details on the implementation.
