### ISSUE TITLE
Support cancelling in-flight tool use

### ISSUE THREAD

**Issue by jspahrsummers** [modelcontextprotocol/modelcontextprotocol#9]

**Comment by jspahrsummers** [comment]
This isn't supported by Anthropic's tool use API, so probably little point in including it in MCP for now.

**Comment by connor4312** [comment]
VS Code is looking to become an MCP client shortly, and would be quite interested in having tool cancellation.

**Comment by fabioz** [comment]
Hey @jspahrsummers, while not initially planned, would it be possible to reconsider this going forward? We (at Sema4.ai) would have interest in this too (and could provide help to improve the spec if needed)...
